apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: chaos-network-bandwidth-application
  namespace: application
spec:
  action: bandwidth
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: ratings
  bandwidth:
    rate: "500kbps"
  duration: "60m"
