apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: chaos-pod-failure-application
  namespace: application
spec:
  action: pod-failure
  mode: one
  selector:
    namespaces:
      - application
  duration: "60m"
