apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: chaos-cpu-stress-application
  namespace: application
spec:
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: ratings
  stressors:
    cpu:
      workers: 2
      load: 15
  duration: "60m"
