apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: chaos-network-partition-application
  namespace: application
spec:
  action: partition
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: catalogue
  direction: both
  target:
    mode: all
    selector:
      namespaces:
        - application
      expressionSelectors:
        - { key: app, operator: In, values: [cart, web] }
  duration: "60m"
