apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: chaos-io-latency-application
  namespace: application
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: web
  volumePath: "/var/lib/mysql"
  path: ""
  delay: "200ms"
  percent: 50
  duration: "60m"
