apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: chaos-memory-stress-application
  namespace: application
spec:
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: web
  stressors:
    memory:
      workers: 2
      size: "128MB"
  duration: "60m"
