apiVersion: v1
kind: ConfigMap
metadata:
  name: linkerd-config
  namespace: ${NAMESPACE}
data:
  global: |
    linkerdNamespace: ${NAMESPACE}
    clusterDomain: cluster.local
  proxy: |
    destinationGetAddress: linkerd-dst-headless.${NAMESPACE}.svc.cluster.local:8086
    policyGetAddress: linkerd-policy.${NAMESPACE}.svc.cluster.local:8090
    identityContext:
      trustAnchorsPem: "${CA_CERT}"
      trustDomain: cluster.local