linkerdNamespace: bastion
nodeSelector:
  kubernetes.io/os: linux
  role: bastion

tolerations:
  - key: dedicated
    operator: Equal
    value: bastion
    effect: NoSchedule

identityTrustDomain: cluster.local

prometheusUrl: http://prometheus.bastion.svc.cluster.local:9090

# Disable dashboard
#dashboard:
#  replicas: 0