apiVersion: chaos-mesh.org/v1alpha1
kind: HTTPChaos
metadata:
  name: chaos-http-abort-application
  namespace: application
spec:
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: payment
  target: Response
  port: 8080
  duration: "60m"
  replace:
    code: 503
    body: U2VydmljZSBpcyBjdXJyZW50bHkgdW5hdmFpbGFibGU=
