apiVersion: chaos-mesh.org/v1alpha1
kind: StressChaos
metadata:
  name: chaos-cpu-stress-application
  namespace: application
spec:
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: dispatch
  stressors:
    cpu:
      workers: 3
      load: 80
  duration: "60m"
