apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: chaos-io-latency-application
  namespace: application
spec:
  action: delay
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: redis
  delay:
    latency: "500ms"
    correlation: "50"
    jitter: "0ms"
  duration: "60m"
