apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: chaos-io-latency-application
  namespace: application
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: redis
  volumePath: "/data"
  path: ""
  delay: "500ms"
  percent: 50
  duration: "60m"
