apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: chaos-network-partition-application
  namespace: application
spec:
  action: partition
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: user
  direction: from
  target:
    selector:
      namespaces:
        - application
      labelSelectors:
        app: user
    mode: one
  duration: "60m"
