apiVersion: chaos-mesh.org/v1alpha1
kind: NetworkChaos
metadata:
  name: chaos-network-bandwidth-application
  namespace: application
spec:
  action: bandwidth
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: user
  bandwidth:
    rate: "1mbps"
  duration: "60m"
