apiVersion: chaos-mesh.org/v1alpha1
kind: PodChaos
metadata:
  name: chaos-pod-kill-application
  namespace: application
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: ratings
  duration: "60m"
