apiVersion: chaos-mesh.org/v1alpha1
kind: IOChaos
metadata:
  name: chaos-io-latency-application
  namespace: application
spec:
  action: latency
  mode: one
  selector:
    namespaces:
      - application
    labelSelectors:
      app: mongo
  volumePath: "/data"
  path: ""
  delay: "300ms"
  percent: 100
  duration: "60m"
